/**
 * ThingsBoard, Inc. ("COMPANY") CONFIDENTIAL
 *
 * Copyright © 2016-2022 ThingsBoard, Inc. All Rights Reserved.
 *
 * NOTICE: All information contained herein is, and remains
 * the property of ThingsBoard, Inc. and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to ThingsBoard, Inc.
 * and its suppliers and may be covered by U.S. and Foreign Patents,
 * patents in process, and are protected by trade secret or copyright law.
 *
 * Dissemination of this information or reproduction of this material is strictly forbidden
 * unless prior written permission is obtained from COMPANY.
 *
 * Access to the source code contained herein is hereby forbidden to anyone except current COMPANY employees,
 * managers or contractors who have executed Confidentiality and Non-disclosure agreements
 * explicitly covering such access.
 *
 * The copyright notice above does not evidence any actual or intended publication
 * or disclosure  of  this source code, which includes
 * information that is confidential and/or proprietary, and is a trade secret, of  COMPANY.
 * ANY REPRODUCTION, MODIFICATION, DISTRIBUTION, PUBLIC  PERFORMANCE,
 * OR PUBLIC DISPLAY OF OR THROUGH USE  OF THIS  SOURCE CODE  WITHOUT
 * THE EXPRESS WRITTEN CONSENT OF COMPANY IS STRICTLY PROHIBITED,
 * AND IN VIOLATION OF APPLICABLE LAWS AND INTERNATIONAL TREATIES.
 * THE RECEIPT OR POSSESSION OF THIS SOURCE CODE AND/OR RELATED INFORMATION
 * DOES NOT CONVEY OR IMPLY ANY RIGHTS TO REPRODUCE, DISCLOSE OR DISTRIBUTE ITS CONTENTS,
 * OR TO MANUFACTURE, USE, OR SELL ANYTHING THAT IT  MAY DESCRIBE, IN WHOLE OR IN PART.
 */
package org.thingsboard.server.edge;

import com.google.protobuf.AbstractMessage;
import org.junit.Assert;
import org.junit.Test;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.thingsboard.server.common.data.Customer;
import org.thingsboard.server.gen.edge.v1.CustomerUpdateMsg;
import org.thingsboard.server.gen.edge.v1.UpdateMsgType;

import java.util.List;

import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

abstract public class BaseCustomerEdgeTest extends AbstractEdgeTest {

    @Test
    public void testCreateUpdateDeleteCustomer() throws Exception {
        edgeImitator.expectMessageAmount(1);
        // create customer A
        Customer customerA = new Customer();
        customerA.setTitle("Edge Customer A");
        Customer savedCustomerA = doPost("/api/customer", customerA, Customer.class);
        // create sub customer A
        Customer subCustomerA = new Customer();
        subCustomerA.setTitle("Edge Sub Customer A");
        subCustomerA.setParentCustomerId(savedCustomerA.getId());
        Customer savedSubCustomerA = doPost("/api/customer", subCustomerA, Customer.class);
        // create sub sub customer A
        Customer subSubCustomerA = new Customer();
        subSubCustomerA.setTitle("Edge Sub Sub Customer A");
        subSubCustomerA.setParentCustomerId(savedSubCustomerA.getId());
        Customer savedSubSubCustomerA = doPost("/api/customer", subSubCustomerA, Customer.class);
        // create customer B
        Customer customerB = new Customer();
        customerB.setTitle("Edge Customer B");
        Customer savedCustomerB = doPost("/api/customer", customerB, Customer.class);
        Assert.assertFalse(edgeImitator.waitForMessages(1));

        // change owner of edge from tenant to sub customer A
        edgeImitator.expectMessageAmount(2);
        doPost("/api/owner/CUSTOMER/" + savedSubCustomerA.getId().getId() + "/EDGE/" + edge.getId().getId());
        Assert.assertTrue(edgeImitator.waitForMessages());
        List<CustomerUpdateMsg> customerUpdateMsgs = edgeImitator.findAllMessagesByType(CustomerUpdateMsg.class);
        Assert.assertEquals(2, customerUpdateMsgs.size());

        CustomerUpdateMsg customerAUpdateMsg = customerUpdateMsgs.get(0);
        Assert.assertEquals(UpdateMsgType.ENTITY_CREATED_RPC_MESSAGE, customerAUpdateMsg.getMsgType());
        Assert.assertEquals(savedCustomerA.getUuidId().getMostSignificantBits(), customerAUpdateMsg.getIdMSB());
        Assert.assertEquals(savedCustomerA.getUuidId().getLeastSignificantBits(), customerAUpdateMsg.getIdLSB());
        Assert.assertEquals(savedCustomerA.getTitle(), customerAUpdateMsg.getTitle());
        testAutoGeneratedCodeByProtobuf(customerAUpdateMsg);

        CustomerUpdateMsg subCustomerAUpdateMsg = customerUpdateMsgs.get(0);
        Assert.assertEquals(UpdateMsgType.ENTITY_CREATED_RPC_MESSAGE, subCustomerAUpdateMsg.getMsgType());
        Assert.assertEquals(savedSubCustomerA.getUuidId().getMostSignificantBits(), subCustomerAUpdateMsg.getIdMSB());
        Assert.assertEquals(savedSubCustomerA.getUuidId().getLeastSignificantBits(), subCustomerAUpdateMsg.getIdLSB());
        Assert.assertEquals(savedSubCustomerA.getTitle(), subCustomerAUpdateMsg.getTitle());


        // update customer A and validate changes on edge
        // update sub customer and validate changes on edge
        // update sub sub customer and validate NO changes on edge
        // update customer B and validate NO changes on edge





        // update customer
//        edgeImitator.expectMessageAmount(1);
//        savedCustomer.setTitle("Edge Customer Updated");
//        savedCustomer = doPost("/api/customer", savedCustomer, Customer.class);
//        Assert.assertTrue(edgeImitator.waitForMessages());
//        latestMessage = edgeImitator.getLatestMessage();
//        Assert.assertTrue(latestMessage instanceof CustomerUpdateMsg);
//        customerUpdateMsg = (CustomerUpdateMsg) latestMessage;
//        Assert.assertEquals(UpdateMsgType.ENTITY_UPDATED_RPC_MESSAGE, customerUpdateMsg.getMsgType());
//        Assert.assertEquals(savedCustomer.getUuidId().getMostSignificantBits(), customerUpdateMsg.getIdMSB());
//        Assert.assertEquals(savedCustomer.getUuidId().getLeastSignificantBits(), customerUpdateMsg.getIdLSB());
//        Assert.assertEquals(savedCustomer.getTitle(), customerUpdateMsg.getTitle());
//
//        // delete customer
//        edgeImitator.expectMessageAmount(1);
//        doDelete("/api/customer/" + savedCustomer.getUuidId())
//                .andExpect(status().isOk());
//        Assert.assertTrue(edgeImitator.waitForMessages());
//        latestMessage = edgeImitator.getLatestMessage();
//        Assert.assertTrue(latestMessage instanceof CustomerUpdateMsg);
//        customerUpdateMsg = (CustomerUpdateMsg) latestMessage;
//        Assert.assertEquals(UpdateMsgType.ENTITY_DELETED_RPC_MESSAGE, customerUpdateMsg.getMsgType());
//        Assert.assertEquals(customerUpdateMsg.getIdMSB(), savedCustomer.getUuidId().getMostSignificantBits());
//        Assert.assertEquals(customerUpdateMsg.getIdLSB(), savedCustomer.getUuidId().getLeastSignificantBits());
    }

    @Test
    public void testChangeOwnerOfCustomer_validateChangesToEdgeEntityGroups() {

    }

}
