#
# SPDX-FileCopyrightText: Copyright The Thingsboard Authors
# SPDX-License-Identifier: Apache-2.0
#

services:
  postgres:
    restart: always
    image: "postgres:16"
    ports:
      - "5432"
    environment:
      POSTGRES_DB: tb_edge
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./tb-edge/postgres:/var/lib/postgresql/data
  tb-edge1:
    env_file:
      - tb-edge.postgres.env
    depends_on:
      - postgres
  tb-edge2:
    env_file:
      - tb-edge.postgres.env
    depends_on:
      - postgres
  tb-edge3:
    env_file:
      - tb-edge.postgres.env
    depends_on:
      - postgres