#
# SPDX-FileCopyrightText: Copyright The Thingsboard Authors
# SPDX-License-Identifier: Apache-2.0
#

services:
  # Redis sentinel
  # The latest version of Redis compatible with ThingsBoard is 7.2
  redis-master:
    image: 'bitnamilegacy/redis:7.2'
    volumes:
      - ./tb-edge/redis-sentinel-data-master:/bitnami/redis/data
    environment:
      - 'REDIS_REPLICATION_MODE=master'
      - 'REDIS_PASSWORD=thingsboard'

  redis-slave:
    image: 'bitnamilegacy/redis:7.2'
    volumes:
      - ./tb-edge/redis-sentinel-data-slave:/bitnami/redis/data
    environment:
      - 'REDIS_REPLICATION_MODE=slave'
      - 'REDIS_MASTER_HOST=redis-master'
      - 'REDIS_MASTER_PASSWORD=thingsboard'
      - 'REDIS_PASSWORD=thingsboard'
    depends_on:
      - redis-master

  redis-sentinel:
    image: 'bitnamilegacy/redis-sentinel:7.2'
    volumes:
      - ./tb-edge/redis-sentinel-data-sentinel:/bitnami/redis/data
    environment:
      - 'REDIS_MASTER_HOST=redis-master'
      - 'REDIS_MASTER_SET=mymaster'
      - 'REDIS_SENTINEL_PASSWORD=sentinel'
      - 'REDIS_MASTER_PASSWORD=thingsboard'
    depends_on:
      - redis-master
      - redis-slave

  # ThingsBoard Edge setup to use redis-sentinel
  tb-edge1:
    env_file:
      - cache-redis-sentinel.env
    depends_on:
      - redis-sentinel
  tb-edge2:
    env_file:
      - cache-redis-sentinel.env
    depends_on:
      - redis-sentinel
  tb-edge3:
    env_file:
      - cache-redis-sentinel.env
    depends_on:
      - redis-sentinel