#
# SPDX-FileCopyrightText: Copyright The Thingsboard Authors
# SPDX-License-Identifier: Apache-2.0
#

services:
# Redis standalone
# The latest version of Redis compatible with ThingsBoard is 7.2
  redis:
    restart: always
    image: bitnamilegacy/redis:7.2
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '6379:6379'
    volumes:
      - ./tb-edge/redis-data:/bitnami/redis/data

# ThingsBoard setup to use redis-standalone
  tb-edge1:
    env_file:
      - cache-redis.env
    depends_on:
      - redis
  tb-edge2:
    env_file:
      - cache-redis.env
    depends_on:
      - redis
  tb-edge3:
    env_file:
      - cache-redis.env
    depends_on:
      - redis